ifneq ($(TARGET_DISABLE_AIS_DLKM),true)
ifneq ($(TARGET_IS_HEADLESS),true)
ifneq ($(TARGET_USES_QMAA_OVERRIDE_CAMERA),true)
PRODUCT_PACKAGES += ais.ko
endif #TARGET_USES_QMAA_OVERRIDE_CAMERA
endif #TARGET_IS_HEADLESS
endif # TARGET_DISABLE_AIS_DLKM
