/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2024, Qualcomm Innovation Center, Inc. All rights reserved.
 */

#ifndef _CAM_IFE_CSID_LITE_690_H_
#define _CAM_IFE_CSID_LITE_690_H_

#include "cam_ife_csid_common.h"
#include "cam_ife_csid_dev.h"
#include "cam_ife_csid_hw_ver2.h"
#include "cam_irq_controller.h"
#include "cam_isp_hw_mgr_intf.h"

static uint32_t cam_ife_csid_690_lite_num_top_regs[] = {0,};

static const struct cam_ife_csid_irq_desc cam_ife_csid_lite_690_rx_irq_desc[][32] = {
	{
		{
			.bitmask = BIT(0),
			.desc = "DL0_EOT",
		},
		{
			.bitmask = BIT(1),
			.desc = "DL1_EOT",
		},
		{
			.bitmask = BIT(2),
			.desc = "DL2_EOT",
		},
		{
			.bitmask = BIT(3),
			.desc = "DL3_EOT",
		},
		{
			.bitmask = BIT(4),
			.desc = "DL0_SOT",
		},
		{
			.bitmask = BIT(5),
			.desc = "DL1_SOT",
		},
		{
			.bitmask = BIT(6),
			.desc = "DL2_SOT",
		},
		{
			.bitmask = BIT(7),
			.desc = "DL3_SOT",
		},
		{
			.bitmask = BIT(8),
			.desc = "LONG_PKT",
		},
		{
			.bitmask = BIT(9),
			.desc = "SHORT_PKT",
		},
		{
			.bitmask = BIT(10),
			.desc = "CPHY_PKT_HDR",
		},
		{
			.bitmask = BIT(11),
			.desc = "ERROR_CPHY_EOT_RECEPTION",
		},
		{
			.bitmask = BIT(12),
			.desc = "ERROR_CPHY_SOT_RECEPTION",
		},
		{
			.bitmask = BIT(13),
			.desc = "ERROR_CPHY_PH_CRC",
		},
		{
			.bitmask = BIT(14),
			.desc = "WARNING_ECC",
		},
		{
			.bitmask = BIT(15),
			.desc = "ERROR_LANE0_FIFO_OVERFLOW",
		},
		{
			.bitmask = BIT(16),
			.desc = "ERROR_LANE1_FIFO_OVERFLOW",
		},
		{
			.bitmask = BIT(17),
			.desc = "ERROR_LANE2_FIFO_OVERFLOW",
		},
		{
			.bitmask = BIT(18),
			.desc = "ERROR_LANE3_FIFO_OVERFLOW",
		},
		{
			.bitmask = BIT(19),
			.desc = "ERROR_CRC",
		},
		{
			.bitmask = BIT(20),
			.desc = "ERROR_ECC",
		},
		{
			.bitmask = BIT(21),
			.desc = "ERROR_MMAPPED_VC_DT",
		},
		{
			.bitmask = BIT(22),
			.desc = "ERROR_UNMAPPED_VC_DT",
		},
		{
			.bitmask = BIT(23),
			.desc = "ERROR_STREAM_UNDERFLOW",
		},
		{
			.bitmask = BIT(24),
			.desc = "ERROR_UNBOUNDED_FRAME",
		},
	},
	{}
};

static const struct cam_ife_csid_irq_desc cam_ife_csid_lite_690_path_irq_desc[] = {
	{
		.bitmask = BIT(0),
		.desc = "ERROR_FREEZE_FRAME_IRQ",
	},
	{
		.bitmask = BIT(1),
		.desc = "",
	},
	{
		.bitmask = BIT(2),
		.desc = "ERROR_FIFO_OVERFLOW",
	},
	{
		.bitmask = BIT(3),
		.desc = "CAMIF_EOF",
	},
	{
		.bitmask = BIT(4),
		.desc = "CAMIF_SOF",
	},
	{
		.bitmask = BIT(5),
		.desc = "FRAME_DROP_EOF",
	},
	{
		.bitmask = BIT(6),
		.desc = "FRAME_DROP_EOL",
	},
	{
		.bitmask = BIT(7),
		.desc = "FRAME_DROP_SOL",
	},
	{
		.bitmask = BIT(8),
		.desc = "FRAME_DROP_SOF",
	},
	{
		.bitmask = BIT(9),
		.desc = "INFO_INPUT_EOF",
	},
	{
		.bitmask = BIT(10),
		.desc = "INFO_INPUT_EOL",
	},
	{
		.bitmask = BIT(11),
		.desc = "INFO_INPUT_SOL",
	},
	{
		.bitmask = BIT(12),
		.desc = "INFO_INPUT_SOF",
	},
	{
		.bitmask = BIT(13),
		.err_type = CAM_ISP_HW_ERROR_CSID_FRAME_SIZE,
		.desc = "ERROR_PIX_COUNT",
		.err_handler = cam_ife_csid_ver2_print_format_measure_info,
	},
	{
		.bitmask = BIT(14),
		.err_type = CAM_ISP_HW_ERROR_CSID_FRAME_SIZE,
		.desc = "ERROR_PIX_COUNT",
		.err_handler = cam_ife_csid_ver2_print_format_measure_info,
	},
	{
		.bitmask = BIT(15),
		.desc = "VCDT_GRP1_SEL",
	},
	{
		.bitmask = BIT(16),
		.desc = "VCDT_GRP0_SEL",
	},
	{
		.bitmask = BIT(17),
		.desc = "VCDT_GRP_CHANGE",
	},
	{
		.bitmask = BIT(18),
		.desc = "FRAME_DROP",
	},
	{
		.bitmask = BIT(19),
		.err_type = CAM_ISP_HW_ERROR_RECOVERY_OVERFLOW,
		.desc = "OVERFLOW_RECOVERY: Back pressure/output fifo ovrfl",
	},
	{
		.bitmask = BIT(20),
		.desc = "ERROR_REC_CCIF_VIOLATION From Camif",
	},
	{
		.bitmask = BIT(21),
		.desc = "CAMIF_EPOCH0",
	},
	{
		.bitmask = BIT(22),
		.desc = "CAMIF_EPOCH1",
	},
	{
		.bitmask = BIT(23),
		.desc = "RUP_DONE",
	},
	{
		.bitmask = BIT(24),
		.desc = "ILLEGAL_BATCH_ID",
	},
	{
		.bitmask = BIT(25),
		.desc = "BATCH_END_MISSING_VIOLATION",
	},
	{
		.bitmask = BIT(26),
		.desc = "HEIGHT_OVERFLOW_VIOLATION",
	},
	{
		.bitmask = BIT(27),
		.desc = "WIDTH_OVERFLOW_VIOLATION",
	},
	{
		.bitmask = BIT(28),
		.desc = "HEIGHT_UNDERFLOW_VIOLATION",
	},
	{
		.bitmask = BIT(29),
		.desc = "WIDTH_UNDERFLOW_VIOLATION",
	},
	{
		.bitmask = BIT(30),
		.desc = "SENSOR_SWITCH_OUT_OF_SYNC_FRAME_DROP",
		.err_handler = cam_ife_csid_hw_ver2_mup_mismatch_handler,
	},
	{
		.bitmask = BIT(31),
		.desc = "CCIF_VIOLATION: Bad frame timings",
	},
};
static struct cam_irq_register_set cam_ife_csid_lite_690_irq_reg_set[CAM_IFE_CSID_IRQ_REG_MAX] = {
	/* Top */
	{
		.mask_reg_offset   = 0x00000080,
		.clear_reg_offset  = 0x00000084,
		.status_reg_offset = 0x0000007C,
		.set_reg_offset    = 0x00000088,
		.test_set_val      = BIT(0),
		.test_sub_val      = BIT(0),
	},
	/* RX */
	{
		.mask_reg_offset   = 0x000000A0,
		.clear_reg_offset  = 0x000000A4,
		.status_reg_offset = 0x0000009C,
	},
	/* RDI0 */
	{
		.mask_reg_offset   = 0x000000F0,
		.clear_reg_offset  = 0x000000F4,
		.status_reg_offset = 0x000000EC,
	},
	/* RDI1 */
	{
		.mask_reg_offset   = 0x00000100,
		.clear_reg_offset  = 0x00000104,
		.status_reg_offset = 0x000000FC,
	},
	/* RDI2 */
	{
		.mask_reg_offset   = 0x00000110,
		.clear_reg_offset  = 0x00000114,
		.status_reg_offset = 0x0000010C,
	},
	/* RDI3 */
	{
		.mask_reg_offset   = 0x00000120,
		.clear_reg_offset  = 0x00000124,
		.status_reg_offset = 0x0000011C,
	},
	/* RDI4 */
	{
		.mask_reg_offset   = 0x00000130,
		.clear_reg_offset  = 0x00000134,
		.status_reg_offset = 0x0000012C,
	},
	/* RDI5 */
	{
		.mask_reg_offset   = 0x00000140,
		.clear_reg_offset  = 0x00000144,
		.status_reg_offset = 0x0000013C,
	},
};

static struct cam_irq_controller_reg_info cam_ife_csid_lite_690_top_irq_reg_info = {
	.num_registers = 1,
	.irq_reg_set = &cam_ife_csid_lite_690_irq_reg_set[CAM_IFE_CSID_IRQ_REG_TOP],
	.global_irq_cmd_offset = 0x00000014,
	.global_set_bitmask    = 0x00000010,
	.global_clear_bitmask  = 0x00000001,
	.clear_all_bitmask     = 0xFFFFFFFF,
};

static struct cam_irq_controller_reg_info cam_ife_csid_lite_690_rx_irq_reg_info = {
	.num_registers = 1,
	.irq_reg_set = &cam_ife_csid_lite_690_irq_reg_set[CAM_IFE_CSID_IRQ_REG_RX], /* RX */
	.global_irq_cmd_offset = 0,
};

static struct cam_irq_controller_reg_info
		cam_ife_csid_lite_690_path_irq_reg_info[CAM_IFE_PIX_PATH_RES_MAX] = {
	{
		.num_registers = 1,
		.irq_reg_set = &cam_ife_csid_lite_690_irq_reg_set[CAM_IFE_CSID_IRQ_REG_RDI_0],
		.global_irq_cmd_offset = 0,
	},
	{
		.num_registers = 1,
		.irq_reg_set = &cam_ife_csid_lite_690_irq_reg_set[CAM_IFE_CSID_IRQ_REG_RDI_1],
		.global_irq_cmd_offset = 0,
	},
	{
		.num_registers = 1,
		.irq_reg_set = &cam_ife_csid_lite_690_irq_reg_set[CAM_IFE_CSID_IRQ_REG_RDI_2],
		.global_irq_cmd_offset = 0,
	},
	{
		.num_registers = 1,
		.irq_reg_set = &cam_ife_csid_lite_690_irq_reg_set[CAM_IFE_CSID_IRQ_REG_RDI_3],
		.global_irq_cmd_offset = 0,
	},
	{
		.num_registers = 1,
		.irq_reg_set = &cam_ife_csid_lite_690_irq_reg_set[CAM_IFE_CSID_IRQ_REG_RDI_4],
		.global_irq_cmd_offset = 0,
	},
	{
		.num_registers = 1,
		.irq_reg_set = &cam_ife_csid_lite_690_irq_reg_set[CAM_IFE_CSID_IRQ_REG_RDI_5],
		.global_irq_cmd_offset = 0,
	},
};

static struct cam_irq_register_set cam_ife_csid_lite_690_buf_done_irq_reg_set[1] = {
	{
		.mask_reg_offset   = 0x00000090,
		.clear_reg_offset  = 0x00000094,
		.status_reg_offset = 0x0000008C,
	},
};

static struct cam_irq_controller_reg_info
	cam_ife_csid_lite_690_buf_done_irq_reg_info = {
	.num_registers = 1,
	.irq_reg_set = cam_ife_csid_lite_690_buf_done_irq_reg_set,
	.global_irq_cmd_offset = 0, /* intentionally set to zero */
};

static struct cam_ife_csid_ver2_common_reg_info
			cam_ife_csid_lite_690_cmn_reg_info = {
	.hw_version_addr                         = 0x0,
	.cfg0_addr                               = 0x4,
	.global_cmd_addr                         = 0x8,
	.reset_cfg_addr                          = 0xC,
	.reset_cmd_addr                          = 0x10,
	.irq_cmd_addr                            = 0x14,
	.rup_aup_cmd_addr                        = 0x18,
	.offline_cmd_addr                        = 0x1C,
	.shdr_master_slave_cfg_addr              = 0x20,
	.top_irq_status_addr                     = {0x7C,},
	.top_irq_mask_addr                       = {0x80,},
	.top_irq_clear_addr                      = {0x84,},
	.top_irq_set_addr                        = {0x88,},
	.buf_done_irq_status_addr                = 0x8C,
	.buf_done_irq_mask_addr                  = 0x90,
	.buf_done_irq_clear_addr                 = 0x94,
	.buf_done_irq_set_addr                   = 0x98,

	/*configurations */
	.major_version                                = 6,
	.minor_version                                = 9,
	.version_incr                                 = 0,
	.num_rdis                                     = 6,
	.num_pix                                      = 0,
	.num_ppp                                      = 0,
	.rst_done_shift_val                           = 1,
	.path_en_shift_val                            = 31,
	.dt_id_shift_val                              = 27,
	.vc_shift_val                                 = 22,
	.dt_shift_val                                 = 16,
	.crop_shift_val                               = 16,
	.decode_format_shift_val                      = 12,
	.decode_format1_supported                     = false,
	.frame_id_decode_en_shift_val                 = 1,
	.multi_vcdt_vc1_shift_val                     = 2,
	.multi_vcdt_dt1_shift_val                     = 7,
	.multi_vcdt_ts_combo_en_shift_val             = 13,
	.multi_vcdt_en_shift_val                      = 0,
	.timestamp_stb_sel_shift_val                  = 0,
	.vfr_en_shift_val                             = 0,
	.mup_shift_val                                = 28,
	.early_eof_supported                          = 1,
	.vfr_supported                                = 1,
	.multi_vcdt_supported                         = 1,
	.ts_comb_vcdt_en                              = true,
	.ts_comb_vcdt_mask                            = 3,
	.frame_id_dec_supported                       = 1,
	.measure_en_hbi_vbi_cnt_mask                  = 0xc,
	.measure_pixel_line_en_mask                   = 0x3,
	.crop_pix_start_mask                          = 0x3fff,
	.crop_pix_end_mask                            = 0xffff,
	.crop_line_start_mask                         = 0x3fff,
	.crop_line_end_mask                           = 0xffff,
	.drop_supported                               = 1,
	.ipp_irq_mask_all                             = 0xFFFFFFFF,
	.rdi_irq_mask_all                             = 0xFFFFFFFF,
	.rst_loc_path_only_val                        = 0x0,
	.rst_location_shift_val                       = 4,
	.rst_loc_complete_csid_val                    = 0x1,
	.rst_mode_frame_boundary_val                  = 0x0,
	.rst_mode_immediate_val                       = 0x1,
	.rst_cmd_hw_reset_complete_val                = 0x1,
	.rst_cmd_sw_reset_complete_val                = 0x2,
	.rst_cmd_irq_ctrl_only_val                    = 0x4,
	.timestamp_strobe_val                         = 0x2,
	.top_reset_irq_mask                           = {0x1,},
	.top_buf_done_irq_mask                        = 0x4000,
	.global_reset                                 = 1,
	.rup_supported                                = 1,
	.only_master_rup                              = 1,
	.phy_sel_base_idx                             = 1,
	.camif_irq_support                            = true,
};

static struct cam_ife_csid_ver2_csi2_rx_reg_info
	cam_ife_csid_lite_690_csi2_reg_info = {
		.irq_status_addr                      = {0x9C,},
		.irq_mask_addr                        = {0xA0,},
		.irq_clear_addr                       = {0xA4,},
		.irq_set_addr                         = {0xA8,},
		/*CSI2 rx control */
		.cfg0_addr                            = 0x200,
		.cfg1_addr                            = 0x204,
		.capture_ctrl_addr                    = 0x208,
		.rst_strobes_addr                     = 0x20C,
		.cap_unmap_long_pkt_hdr_0_addr        = 0x210,
		.cap_unmap_long_pkt_hdr_1_addr        = 0x214,
		.captured_short_pkt_0_addr            = 0x218,
		.captured_short_pkt_1_addr            = 0x21C,
		.captured_long_pkt_0_addr             = 0x220,
		.captured_long_pkt_1_addr             = 0x224,
		.captured_long_pkt_ftr_addr           = 0x228,
		.captured_cphy_pkt_hdr_addr           = 0x22C,
		.lane0_misr_addr                      = 0x230,
		.lane1_misr_addr                      = 0x234,
		.lane2_misr_addr                      = 0x238,
		.lane3_misr_addr                      = 0x23C,
		.total_pkts_rcvd_addr                 = 0x240,
		.stats_ecc_addr                       = 0x244,
		.total_crc_err_addr                   = 0x248,
		.de_scramble_type3_cfg0_addr          = 0x24C,
		.de_scramble_type3_cfg1_addr          = 0x250,
		.de_scramble_type2_cfg0_addr          = 0x254,
		.de_scramble_type2_cfg1_addr          = 0x258,
		.de_scramble_type1_cfg0_addr          = 0x25C,
		.de_scramble_type1_cfg1_addr          = 0x260,
		.de_scramble_type0_cfg0_addr          = 0x264,
		.de_scramble_type0_cfg1_addr          = 0x268,

		.rst_done_shift_val                   = 27,
		.irq_mask_all                         = 0xFFFFFFF,
		.misr_enable_shift_val                = 6,
		.vc_mode_shift_val                    = 2,
		.capture_long_pkt_en_shift            = 0,
		.capture_short_pkt_en_shift           = 1,
		.capture_cphy_pkt_en_shift            = 2,
		.capture_long_pkt_dt_shift            = 4,
		.capture_long_pkt_vc_shift            = 10,
		.capture_short_pkt_vc_shift           = 15,
		.capture_cphy_pkt_dt_shift            = 20,
		.capture_cphy_pkt_vc_shift            = 26,
		.phy_num_mask                         = 0xf,
		.vc_mask                              = 0x7C00000,
		.dt_mask                              = 0x3f0000,
		.wc_mask                              = 0xffff,
		.vc_shift                             = 0x16,
		.dt_shift                             = 0x10,
		.wc_shift                             = 0,
		.calc_crc_mask                        = 0xffff,
		.expected_crc_mask                    = 0xffff,
		.calc_crc_shift                       = 0x10,
		.ecc_correction_shift_en              = 0,
		.lane_num_shift                       = 0,
		.lane_cfg_shift                       = 4,
		.phy_type_shift                       = 24,
		.phy_num_shift                        = 20,
		.tpg_mux_en_shift                     = 27,
		.tpg_num_sel_shift                    = 28,
		.phy_bist_shift_en                    = 7,
		.epd_mode_shift_en                    = 8,
		.eotp_shift_en                        = 9,
		.dyn_sensor_switch_shift_en           = 10,
		.long_pkt_strobe_rst_shift            = 0,
		.short_pkt_strobe_rst_shift           = 1,
		.cphy_pkt_strobe_rst_shift            = 2,
		.unmapped_pkt_strobe_rst_shift        = 3,
		.top_irq_mask                         = {0x4,},
		.fatal_err_mask                       = {0x19FA800,},
		.part_fatal_err_mask                  = {0x0001000,},
		.non_fatal_err_mask                   = {0x0200000,},
};

static struct cam_ife_csid_ver2_path_reg_info
	cam_ife_csid_lite_690_rdi_0_reg_info = {
		.irq_status_addr            = 0xEC,
		.irq_mask_addr              = 0xF0,
		.irq_clear_addr             = 0xF4,
		.irq_set_addr               = 0xF8,
		.cfg0_addr                  = 0x300,
		.ctrl_addr                  = 0x304,
		.debug_clr_cmd_addr         = 0x308,
		.multi_vcdt_cfg0_addr       = 0x30C,
		.cfg1_addr                  = 0x310,
		.err_recovery_cfg0_addr     = 0x314,
		.err_recovery_cfg1_addr     = 0x318,
		.err_recovery_cfg2_addr     = 0x31C,
		.debug_byte_cntr_ping_addr  = 0x320,
		.debug_byte_cntr_pong_addr  = 0x324,
		.camif_frame_cfg_addr       = 0x328,
		.epoch_irq_cfg_addr         = 0x32C,
		.epoch0_subsample_ptrn_addr = 0x330,
		.epoch1_subsample_ptrn_addr = 0x334,
		.debug_camif_1_addr         = 0x338,
		.debug_camif_0_addr         = 0x33C,
		.frm_drop_pattern_addr      = 0x340,
		.frm_drop_period_addr       = 0x344,
		.irq_subsample_pattern_addr = 0x348,
		.irq_subsample_period_addr  = 0x34C,
		.hcrop_addr                 = 0x350,
		.vcrop_addr                 = 0x354,
		.pix_drop_pattern_addr      = 0x358,
		.pix_drop_period_addr       = 0x35C,
		.line_drop_pattern_addr     = 0x360,
		.line_drop_period_addr      = 0x364,
		.debug_halt_status_addr     = 0x36C,
		.debug_misr_val0_addr       = 0x370,
		.debug_misr_val1_addr       = 0x374,
		.debug_misr_val2_addr       = 0x378,
		.debug_misr_val3_addr       = 0x37C,
		.format_measure_cfg0_addr   = 0x380,
		.format_measure_cfg1_addr   = 0x384,
		.format_measure0_addr       = 0x388,
		.format_measure1_addr       = 0x38C,
		.format_measure2_addr       = 0x390,
		.timestamp_curr0_sof_addr   = 0x394,
		.timestamp_curr1_sof_addr   = 0x398,
		.timestamp_perv0_sof_addr   = 0x39C,
		.timestamp_perv1_sof_addr   = 0x3A0,
		.timestamp_curr0_eof_addr   = 0x3A4,
		.timestamp_curr1_eof_addr   = 0x3A8,
		.timestamp_perv0_eof_addr   = 0x3AC,
		.timestamp_perv1_eof_addr   = 0x3B0,
		.batch_period_cfg_addr      = 0x3BC,
		.batch_stream_id_cfg_addr   = 0x3C0,
		.epoch0_cfg_batch_id0_addr  = 0x3C4,
		.epoch1_cfg_batch_id0_addr  = 0x3C8,
		.epoch0_cfg_batch_id1_addr  = 0x3CC,
		.epoch1_cfg_batch_id1_addr  = 0x3D0,
		.epoch0_cfg_batch_id2_addr  = 0x3D4,
		.epoch1_cfg_batch_id2_addr  = 0x3D8,
		.epoch0_cfg_batch_id3_addr  = 0x3DC,
		.epoch1_cfg_batch_id3_addr  = 0x3E0,
		.epoch0_cfg_batch_id4_addr  = 0x3E4,
		.epoch1_cfg_batch_id4_addr  = 0x3E8,
		.epoch0_cfg_batch_id5_addr  = 0x3EC,
		.epoch1_cfg_batch_id5_addr  = 0x3F0,
		.frame_freeze_crc_cfg0      = 0x3F4,
		.debug_frame_freeze_crc     = 0x3F8,

		/* configurations */
		.resume_frame_boundary          = 1,
		.overflow_ctrl_en               = 1,
		.overflow_ctrl_mode_val         = 0x8,
		.mipi_pack_supported            = 1,
		.packing_fmt_shift_val          = 15,
		.plain_alignment_shift_val      = 11,
		.plain_fmt_shift_val            = 12,
		.crop_v_en_shift_val            = 8,
		.crop_h_en_shift_val            = 7,
		.drop_v_en_shift_val            = 6,
		.drop_h_en_shift_val            = 5,
		.early_eof_en_shift_val         = 14,
		.format_measure_en_shift_val    = 4,
		.timestamp_en_shift_val         = 4,
		.debug_byte_cntr_rst_shift_val  = 2,
		.ccif_violation_en              = 1,
		.fatal_err_mask                 = 0x4,
		.non_fatal_err_mask             = 0x40080000,
		.sof_irq_mask                   = 0x10,
		.rup_irq_mask                   = 0x800000,
		.epoch0_irq_mask                = 0x200000,
		.epoch1_irq_mask                = 0x400000,
		.eof_irq_mask                   = 0x8,
		.rup_aup_mask                   = 0x100010,
		.top_irq_mask                   = {0x100,},
		.epoch0_shift_val               = 16,
		.epoch1_shift_val               = 0,
};

static struct cam_ife_csid_ver2_path_reg_info
	cam_ife_csid_lite_690_rdi_1_reg_info = {
		.irq_status_addr            = 0xFC,
		.irq_mask_addr              = 0x100,
		.irq_clear_addr             = 0x104,
		.irq_set_addr               = 0x108,
		.cfg0_addr                  = 0x400,
		.ctrl_addr                  = 0x404,
		.debug_clr_cmd_addr         = 0x408,
		.multi_vcdt_cfg0_addr       = 0x40c,
		.cfg1_addr                  = 0x410,
		.err_recovery_cfg0_addr     = 0x414,
		.err_recovery_cfg1_addr     = 0x418,
		.err_recovery_cfg2_addr     = 0x41C,
		.debug_byte_cntr_ping_addr  = 0x420,
		.debug_byte_cntr_pong_addr  = 0x424,
		.camif_frame_cfg_addr       = 0x428,
		.epoch_irq_cfg_addr         = 0x42C,
		.epoch0_subsample_ptrn_addr = 0x430,
		.epoch1_subsample_ptrn_addr = 0x434,
		.debug_camif_1_addr         = 0x438,
		.debug_camif_0_addr         = 0x43C,
		.frm_drop_pattern_addr      = 0x440,
		.frm_drop_period_addr       = 0x444,
		.irq_subsample_pattern_addr = 0x448,
		.irq_subsample_period_addr  = 0x44C,
		.hcrop_addr                 = 0x450,
		.vcrop_addr                 = 0x454,
		.pix_drop_pattern_addr      = 0x458,
		.pix_drop_period_addr       = 0x45C,
		.line_drop_pattern_addr     = 0x460,
		.line_drop_period_addr      = 0x464,
		.debug_halt_status_addr     = 0x46C,
		.debug_misr_val0_addr       = 0x470,
		.debug_misr_val1_addr       = 0x474,
		.debug_misr_val2_addr       = 0x478,
		.debug_misr_val3_addr       = 0x47C,
		.format_measure_cfg0_addr   = 0x490,
		.format_measure_cfg1_addr   = 0x484,
		.format_measure0_addr       = 0x488,
		.format_measure1_addr       = 0x48C,
		.format_measure2_addr       = 0x490,
		.timestamp_curr0_sof_addr   = 0x494,
		.timestamp_curr1_sof_addr   = 0x498,
		.timestamp_perv0_sof_addr   = 0x49C,
		.timestamp_perv1_sof_addr   = 0x4A0,
		.timestamp_curr0_eof_addr   = 0x4A4,
		.timestamp_curr1_eof_addr   = 0x4A8,
		.timestamp_perv0_eof_addr   = 0x4AC,
		.timestamp_perv1_eof_addr   = 0x4B0,
		.batch_period_cfg_addr      = 0x4BC,
		.batch_stream_id_cfg_addr   = 0x4C0,
		.epoch0_cfg_batch_id0_addr  = 0x4C4,
		.epoch1_cfg_batch_id0_addr  = 0x4C8,
		.epoch0_cfg_batch_id1_addr  = 0x4CC,
		.epoch1_cfg_batch_id1_addr  = 0x4D0,
		.epoch0_cfg_batch_id2_addr  = 0x4D4,
		.epoch1_cfg_batch_id2_addr  = 0x4D8,
		.epoch0_cfg_batch_id3_addr  = 0x4DC,
		.epoch1_cfg_batch_id3_addr  = 0x4E0,
		.epoch0_cfg_batch_id4_addr  = 0x4E4,
		.epoch1_cfg_batch_id4_addr  = 0x4E8,
		.epoch0_cfg_batch_id5_addr  = 0x4EC,
		.epoch1_cfg_batch_id5_addr  = 0x4F0,
		.frame_freeze_crc_cfg0      = 0x4F4,
		.debug_frame_freeze_crc     = 0x4F8,

		/* configurations */
		.resume_frame_boundary          = 1,
		.overflow_ctrl_en               = 1,
		.overflow_ctrl_mode_val         = 0x8,
		.mipi_pack_supported            = 1,
		.packing_fmt_shift_val          = 15,
		.plain_alignment_shift_val      = 11,
		.plain_fmt_shift_val            = 12,
		.crop_v_en_shift_val            = 8,
		.crop_h_en_shift_val            = 7,
		.drop_v_en_shift_val            = 6,
		.drop_h_en_shift_val            = 5,
		.early_eof_en_shift_val         = 14,
		.format_measure_en_shift_val    = 4,
		.timestamp_en_shift_val         = 4,
		.debug_byte_cntr_rst_shift_val  = 2,
		.ccif_violation_en              = 1,
		.fatal_err_mask                 = 0x4,
		.non_fatal_err_mask             = 0x40080000,
		.sof_irq_mask                   = 0x10,
		.rup_irq_mask                   = 0x800000,
		.epoch0_irq_mask                = 0x200000,
		.epoch1_irq_mask                = 0x400000,
		.eof_irq_mask                   = 0x8,
		.rup_aup_mask                   = 0x200020,
		.top_irq_mask                   = {0x200,},
		.epoch0_shift_val               = 16,
		.epoch1_shift_val               = 0,
};

static struct cam_ife_csid_ver2_path_reg_info
	cam_ife_csid_lite_690_rdi_2_reg_info = {
		.irq_status_addr            = 0x10C,
		.irq_mask_addr              = 0x110,
		.irq_clear_addr             = 0x114,
		.irq_set_addr               = 0x118,
		.cfg0_addr                  = 0x500,
		.ctrl_addr                  = 0x504,
		.debug_clr_cmd_addr         = 0x508,
		.multi_vcdt_cfg0_addr       = 0x50C,
		.cfg1_addr                  = 0x510,
		.err_recovery_cfg0_addr     = 0x514,
		.err_recovery_cfg1_addr     = 0x518,
		.err_recovery_cfg2_addr     = 0x51C,
		.debug_byte_cntr_ping_addr  = 0x520,
		.debug_byte_cntr_pong_addr  = 0x524,
		.camif_frame_cfg_addr       = 0x528,
		.epoch_irq_cfg_addr         = 0x52C,
		.epoch0_subsample_ptrn_addr = 0x530,
		.epoch1_subsample_ptrn_addr = 0x534,
		.debug_camif_1_addr         = 0x538,
		.debug_camif_0_addr         = 0x53C,
		.frm_drop_pattern_addr      = 0x540,
		.frm_drop_period_addr       = 0x544,
		.irq_subsample_pattern_addr = 0x548,
		.irq_subsample_period_addr  = 0x54C,
		.hcrop_addr                 = 0x550,
		.vcrop_addr                 = 0x554,
		.pix_drop_pattern_addr      = 0x558,
		.pix_drop_period_addr       = 0x55C,
		.line_drop_pattern_addr     = 0x560,
		.line_drop_period_addr      = 0x564,
		.debug_halt_status_addr     = 0x56C,
		.debug_misr_val0_addr       = 0x570,
		.debug_misr_val1_addr       = 0x574,
		.debug_misr_val2_addr       = 0x578,
		.debug_misr_val3_addr       = 0x57C,
		.format_measure_cfg0_addr   = 0x580,
		.format_measure_cfg1_addr   = 0x584,
		.format_measure0_addr       = 0x588,
		.format_measure1_addr       = 0x58C,
		.format_measure2_addr       = 0x590,
		.timestamp_curr0_sof_addr   = 0x594,
		.timestamp_curr1_sof_addr   = 0x598,
		.timestamp_perv0_sof_addr   = 0x59C,
		.timestamp_perv1_sof_addr   = 0x5A0,
		.timestamp_curr0_eof_addr   = 0x5A4,
		.timestamp_curr1_eof_addr   = 0x5A8,
		.timestamp_perv0_eof_addr   = 0x5AC,
		.timestamp_perv1_eof_addr   = 0x5B0,
		.batch_period_cfg_addr      = 0x5BC,
		.batch_stream_id_cfg_addr   = 0x5C0,
		.epoch0_cfg_batch_id0_addr  = 0x5C4,
		.epoch1_cfg_batch_id0_addr  = 0x5C8,
		.epoch0_cfg_batch_id1_addr  = 0x5CC,
		.epoch1_cfg_batch_id1_addr  = 0x5D0,
		.epoch0_cfg_batch_id2_addr  = 0x5D4,
		.epoch1_cfg_batch_id2_addr  = 0x5D8,
		.epoch0_cfg_batch_id3_addr  = 0x5DC,
		.epoch1_cfg_batch_id3_addr  = 0x5E0,
		.epoch0_cfg_batch_id4_addr  = 0x5E4,
		.epoch1_cfg_batch_id4_addr  = 0x5E8,
		.epoch0_cfg_batch_id5_addr  = 0x5EC,
		.epoch1_cfg_batch_id5_addr  = 0x5F0,
		.frame_freeze_crc_cfg0      = 0x5F4,
		.debug_frame_freeze_crc     = 0x5F8,

		/* configurations */
		.resume_frame_boundary          = 1,
		.overflow_ctrl_en               = 1,
		.overflow_ctrl_mode_val         = 0x8,
		.mipi_pack_supported            = 1,
		.packing_fmt_shift_val          = 15,
		.plain_alignment_shift_val      = 11,
		.plain_fmt_shift_val            = 12,
		.crop_v_en_shift_val            = 8,
		.crop_h_en_shift_val            = 7,
		.drop_v_en_shift_val            = 6,
		.drop_h_en_shift_val            = 5,
		.early_eof_en_shift_val         = 14,
		.format_measure_en_shift_val    = 4,
		.timestamp_en_shift_val         = 4,
		.debug_byte_cntr_rst_shift_val  = 2,
		.ccif_violation_en              = 1,
		.fatal_err_mask                 = 0x4,
		.non_fatal_err_mask             = 0x40080000,
		.sof_irq_mask                   = 0x10,
		.rup_irq_mask                   = 0x800000,
		.epoch0_irq_mask                = 0x200000,
		.epoch1_irq_mask                = 0x400000,
		.eof_irq_mask                   = 0x8,
		.rup_aup_mask                   = 0x400040,
		.top_irq_mask                   = {0x400,},
		.epoch0_shift_val               = 16,
		.epoch1_shift_val               = 0,
};

static struct cam_ife_csid_ver2_path_reg_info
	cam_ife_csid_lite_690_rdi_3_reg_info = {
		.irq_status_addr            = 0x11C,
		.irq_mask_addr              = 0x120,
		.irq_clear_addr             = 0x124,
		.irq_set_addr               = 0x128,
		.cfg0_addr                  = 0x600,
		.ctrl_addr                  = 0x604,
		.debug_clr_cmd_addr         = 0x608,
		.multi_vcdt_cfg0_addr       = 0x60c,
		.cfg1_addr                  = 0x610,
		.err_recovery_cfg0_addr     = 0x614,
		.err_recovery_cfg1_addr     = 0x618,
		.err_recovery_cfg2_addr     = 0x61C,
		.debug_byte_cntr_ping_addr  = 0x620,
		.debug_byte_cntr_pong_addr  = 0x624,
		.camif_frame_cfg_addr       = 0x628,
		.epoch_irq_cfg_addr         = 0x62C,
		.epoch0_subsample_ptrn_addr = 0x630,
		.epoch1_subsample_ptrn_addr = 0x634,
		.debug_camif_1_addr         = 0x638,
		.debug_camif_0_addr         = 0x63C,
		.frm_drop_pattern_addr      = 0x640,
		.frm_drop_period_addr       = 0x644,
		.irq_subsample_pattern_addr = 0x648,
		.irq_subsample_period_addr  = 0x64C,
		.hcrop_addr                 = 0x650,
		.vcrop_addr                 = 0x654,
		.pix_drop_pattern_addr      = 0x658,
		.pix_drop_period_addr       = 0x65C,
		.line_drop_pattern_addr     = 0x660,
		.line_drop_period_addr      = 0x664,
		.debug_halt_status_addr     = 0x668,
		.debug_misr_val0_addr       = 0x670,
		.debug_misr_val1_addr       = 0x674,
		.debug_misr_val2_addr       = 0x678,
		.debug_misr_val3_addr       = 0x67C,
		.format_measure_cfg0_addr   = 0x680,
		.format_measure_cfg1_addr   = 0x684,
		.format_measure0_addr       = 0x688,
		.format_measure1_addr       = 0x68C,
		.format_measure2_addr       = 0x690,
		.timestamp_curr0_sof_addr   = 0x694,
		.timestamp_curr1_sof_addr   = 0x698,
		.timestamp_perv0_sof_addr   = 0x69C,
		.timestamp_perv1_sof_addr   = 0x6A0,
		.timestamp_curr0_eof_addr   = 0x6A4,
		.timestamp_curr1_eof_addr   = 0x6A8,
		.timestamp_perv0_eof_addr   = 0x6AC,
		.timestamp_perv1_eof_addr   = 0x6B0,
		.batch_period_cfg_addr      = 0x6BC,
		.batch_stream_id_cfg_addr   = 0x6C0,
		.epoch0_cfg_batch_id0_addr  = 0x6C4,
		.epoch1_cfg_batch_id0_addr  = 0x6C8,
		.epoch0_cfg_batch_id1_addr  = 0x6CC,
		.epoch1_cfg_batch_id1_addr  = 0x6D0,
		.epoch0_cfg_batch_id2_addr  = 0x6D4,
		.epoch1_cfg_batch_id2_addr  = 0x6D8,
		.epoch0_cfg_batch_id3_addr  = 0x6DC,
		.epoch1_cfg_batch_id3_addr  = 0x6E0,
		.epoch0_cfg_batch_id4_addr  = 0x6E4,
		.epoch1_cfg_batch_id4_addr  = 0x6E8,
		.epoch0_cfg_batch_id5_addr  = 0x6EC,
		.epoch1_cfg_batch_id5_addr  = 0x6F0,
		.frame_freeze_crc_cfg0      = 0x6F4,
		.debug_frame_freeze_crc     = 0x6F8,

		/* configurations */
		.resume_frame_boundary          = 1,
		.overflow_ctrl_en               = 1,
		.overflow_ctrl_mode_val         = 0x8,
		.mipi_pack_supported            = 1,
		.packing_fmt_shift_val          = 15,
		.plain_alignment_shift_val      = 11,
		.plain_fmt_shift_val            = 12,
		.crop_v_en_shift_val            = 8,
		.crop_h_en_shift_val            = 7,
		.drop_v_en_shift_val            = 6,
		.drop_h_en_shift_val            = 5,
		.early_eof_en_shift_val         = 14,
		.format_measure_en_shift_val    = 4,
		.timestamp_en_shift_val         = 4,
		.debug_byte_cntr_rst_shift_val  = 2,
		.ccif_violation_en              = 1,
		.fatal_err_mask                 = 0x4,
		.non_fatal_err_mask             = 0x40080000,
		.sof_irq_mask                   = 0x10,
		.rup_irq_mask                   = 0x800000,
		.epoch0_irq_mask                = 0x200000,
		.epoch1_irq_mask                = 0x400000,
		.eof_irq_mask                   = 0x8,
		.rup_aup_mask                   = 0x800080,
		.top_irq_mask                   = {0x800,},
		.epoch0_shift_val               = 16,
		.epoch1_shift_val               = 0,
};

static struct cam_ife_csid_ver2_path_reg_info
	cam_ife_csid_lite_690_rdi_4_reg_info = {
		.irq_status_addr            = 0x12C,
		.irq_mask_addr              = 0x130,
		.irq_clear_addr             = 0x134,
		.irq_set_addr               = 0x138,
		.cfg0_addr                  = 0x700,
		.ctrl_addr                  = 0x704,
		.debug_clr_cmd_addr         = 0x708,
		.multi_vcdt_cfg0_addr       = 0x70c,
		.cfg1_addr                  = 0x710,
		.err_recovery_cfg0_addr     = 0x714,
		.err_recovery_cfg1_addr     = 0x718,
		.err_recovery_cfg2_addr     = 0x71C,
		.debug_byte_cntr_ping_addr  = 0x720,
		.debug_byte_cntr_pong_addr  = 0x724,
		.camif_frame_cfg_addr       = 0x728,
		.epoch_irq_cfg_addr         = 0x72C,
		.epoch0_subsample_ptrn_addr = 0x730,
		.epoch1_subsample_ptrn_addr = 0x734,
		.debug_camif_1_addr         = 0x738,
		.debug_camif_0_addr         = 0x73C,
		.frm_drop_pattern_addr      = 0x740,
		.frm_drop_period_addr       = 0x744,
		.irq_subsample_pattern_addr = 0x748,
		.irq_subsample_period_addr  = 0x74C,
		.hcrop_addr                 = 0x750,
		.vcrop_addr                 = 0x754,
		.pix_drop_pattern_addr      = 0x758,
		.pix_drop_period_addr       = 0x75C,
		.line_drop_pattern_addr     = 0x760,
		.line_drop_period_addr      = 0x764,
		.debug_halt_status_addr     = 0x768,
		.debug_misr_val0_addr       = 0x770,
		.debug_misr_val1_addr       = 0x774,
		.debug_misr_val2_addr       = 0x778,
		.debug_misr_val3_addr       = 0x77C,
		.format_measure_cfg0_addr   = 0x780,
		.format_measure_cfg1_addr   = 0x784,
		.format_measure0_addr       = 0x788,
		.format_measure1_addr       = 0x78C,
		.format_measure2_addr       = 0x790,
		.timestamp_curr0_sof_addr   = 0x794,
		.timestamp_curr1_sof_addr   = 0x798,
		.timestamp_perv0_sof_addr   = 0x79C,
		.timestamp_perv1_sof_addr   = 0x7A0,
		.timestamp_curr0_eof_addr   = 0x7A4,
		.timestamp_curr1_eof_addr   = 0x7A8,
		.timestamp_perv0_eof_addr   = 0x7AC,
		.timestamp_perv1_eof_addr   = 0x7B0,
		.batch_period_cfg_addr      = 0x7BC,
		.batch_stream_id_cfg_addr   = 0x7C0,
		.epoch0_cfg_batch_id0_addr  = 0x7C4,
		.epoch1_cfg_batch_id0_addr  = 0x7C8,
		.epoch0_cfg_batch_id1_addr  = 0x7CC,
		.epoch1_cfg_batch_id1_addr  = 0x7D0,
		.epoch0_cfg_batch_id2_addr  = 0x7D4,
		.epoch1_cfg_batch_id2_addr  = 0x7D8,
		.epoch0_cfg_batch_id3_addr  = 0x7DC,
		.epoch1_cfg_batch_id3_addr  = 0x7E0,
		.epoch0_cfg_batch_id4_addr  = 0x7E4,
		.epoch1_cfg_batch_id4_addr  = 0x7E8,
		.epoch0_cfg_batch_id5_addr  = 0x7EC,
		.epoch1_cfg_batch_id5_addr  = 0x7F0,
		.frame_freeze_crc_cfg0      = 0x7F4,
		.debug_frame_freeze_crc     = 0x7F8,

		/* configurations */
		.resume_frame_boundary          = 1,
		.overflow_ctrl_en               = 1,
		.overflow_ctrl_mode_val         = 0x8,
		.mipi_pack_supported            = 1,
		.packing_fmt_shift_val          = 15,
		.plain_alignment_shift_val      = 11,
		.plain_fmt_shift_val            = 12,
		.crop_v_en_shift_val            = 8,
		.crop_h_en_shift_val            = 7,
		.drop_v_en_shift_val            = 6,
		.drop_h_en_shift_val            = 5,
		.early_eof_en_shift_val         = 14,
		.format_measure_en_shift_val    = 4,
		.timestamp_en_shift_val         = 4,
		.debug_byte_cntr_rst_shift_val  = 2,
		.ccif_violation_en              = 1,
		.fatal_err_mask                 = 0x4,
		.non_fatal_err_mask             = 0x40080000,
		.sof_irq_mask                   = 0x10,
		.rup_irq_mask                   = 0x800000,
		.epoch0_irq_mask                = 0x200000,
		.epoch1_irq_mask                = 0x400000,
		.eof_irq_mask                   = 0x8,
		.rup_aup_mask                   = 0x1000100,
		.top_irq_mask                   = {0x1000,},
		.epoch0_shift_val               = 16,
		.epoch1_shift_val               = 0,
};

static struct cam_ife_csid_ver2_path_reg_info
	cam_ife_csid_lite_690_rdi_5_reg_info = {
		.irq_status_addr            = 0x13C,
		.irq_mask_addr              = 0x130,
		.irq_clear_addr             = 0x134,
		.irq_set_addr               = 0x138,
		.cfg0_addr                  = 0x800,
		.ctrl_addr                  = 0x804,
		.debug_clr_cmd_addr         = 0x808,
		.multi_vcdt_cfg0_addr       = 0x80c,
		.cfg1_addr                  = 0x810,
		.err_recovery_cfg0_addr     = 0x814,
		.err_recovery_cfg1_addr     = 0x818,
		.err_recovery_cfg2_addr     = 0x81C,
		.debug_byte_cntr_ping_addr  = 0x820,
		.debug_byte_cntr_pong_addr  = 0x824,
		.camif_frame_cfg_addr       = 0x828,
		.epoch_irq_cfg_addr         = 0x82C,
		.epoch0_subsample_ptrn_addr = 0x830,
		.epoch1_subsample_ptrn_addr = 0x834,
		.debug_camif_1_addr         = 0x838,
		.debug_camif_0_addr         = 0x83C,
		.frm_drop_pattern_addr      = 0x840,
		.frm_drop_period_addr       = 0x844,
		.irq_subsample_pattern_addr = 0x848,
		.irq_subsample_period_addr  = 0x84C,
		.hcrop_addr                 = 0x850,
		.vcrop_addr                 = 0x854,
		.pix_drop_pattern_addr      = 0x858,
		.pix_drop_period_addr       = 0x85C,
		.line_drop_pattern_addr     = 0x860,
		.line_drop_period_addr      = 0x864,
		.debug_halt_status_addr     = 0x868,
		.debug_misr_val0_addr       = 0x870,
		.debug_misr_val1_addr       = 0x874,
		.debug_misr_val2_addr       = 0x878,
		.debug_misr_val3_addr       = 0x87C,
		.format_measure_cfg0_addr   = 0x880,
		.format_measure_cfg1_addr   = 0x884,
		.format_measure0_addr       = 0x888,
		.format_measure1_addr       = 0x88C,
		.format_measure2_addr       = 0x890,
		.timestamp_curr0_sof_addr   = 0x894,
		.timestamp_curr1_sof_addr   = 0x898,
		.timestamp_perv0_sof_addr   = 0x89C,
		.timestamp_perv1_sof_addr   = 0x8A0,
		.timestamp_curr0_eof_addr   = 0x8A4,
		.timestamp_curr1_eof_addr   = 0x8A8,
		.timestamp_perv0_eof_addr   = 0x8AC,
		.timestamp_perv1_eof_addr   = 0x8B0,
		.batch_period_cfg_addr      = 0x8BC,
		.batch_stream_id_cfg_addr   = 0x8C0,
		.epoch0_cfg_batch_id0_addr  = 0x8C4,
		.epoch1_cfg_batch_id0_addr  = 0x8C8,
		.epoch0_cfg_batch_id1_addr  = 0x8CC,
		.epoch1_cfg_batch_id1_addr  = 0x8D0,
		.epoch0_cfg_batch_id2_addr  = 0x8D4,
		.epoch1_cfg_batch_id2_addr  = 0x8D8,
		.epoch0_cfg_batch_id3_addr  = 0x8DC,
		.epoch1_cfg_batch_id3_addr  = 0x8E0,
		.epoch0_cfg_batch_id4_addr  = 0x8E4,
		.epoch1_cfg_batch_id4_addr  = 0x8E8,
		.epoch0_cfg_batch_id5_addr  = 0x8EC,
		.epoch1_cfg_batch_id5_addr  = 0x8F0,
		.frame_freeze_crc_cfg0      = 0x8F4,
		.debug_frame_freeze_crc     = 0x8F8,

		/* configurations */
		.resume_frame_boundary          = 1,
		.overflow_ctrl_en               = 1,
		.overflow_ctrl_mode_val         = 0x8,
		.mipi_pack_supported            = 1,
		.packing_fmt_shift_val          = 15,
		.plain_alignment_shift_val      = 11,
		.plain_fmt_shift_val            = 12,
		.crop_v_en_shift_val            = 8,
		.crop_h_en_shift_val            = 7,
		.drop_v_en_shift_val            = 6,
		.drop_h_en_shift_val            = 5,
		.early_eof_en_shift_val         = 14,
		.format_measure_en_shift_val    = 4,
		.timestamp_en_shift_val         = 4,
		.debug_byte_cntr_rst_shift_val  = 2,
		.ccif_violation_en              = 1,
		.fatal_err_mask                 = 0x4,
		.non_fatal_err_mask             = 0x40080000,
		.sof_irq_mask                   = 0x10,
		.rup_irq_mask                   = 0x800000,
		.epoch0_irq_mask                = 0x200000,
		.epoch1_irq_mask                = 0x400000,
		.eof_irq_mask                   = 0x8,
		.rup_aup_mask                   = 0x2000200,
		.top_irq_mask                   = {0x2000,},
		.epoch0_shift_val               = 16,
		.epoch1_shift_val               = 0,
};

static struct cam_ife_csid_ver2_reg_info cam_ife_csid_lite_690_reg_info = {
	.top_irq_reg_info      = &cam_ife_csid_lite_690_top_irq_reg_info,
	.rx_irq_reg_info       = &cam_ife_csid_lite_690_rx_irq_reg_info,
	.path_irq_reg_info     = {
		&cam_ife_csid_lite_690_path_irq_reg_info[CAM_IFE_PIX_PATH_RES_RDI_0],
		&cam_ife_csid_lite_690_path_irq_reg_info[CAM_IFE_PIX_PATH_RES_RDI_1],
		&cam_ife_csid_lite_690_path_irq_reg_info[CAM_IFE_PIX_PATH_RES_RDI_2],
		&cam_ife_csid_lite_690_path_irq_reg_info[CAM_IFE_PIX_PATH_RES_RDI_3],
		&cam_ife_csid_lite_690_path_irq_reg_info[CAM_IFE_PIX_PATH_RES_RDI_4],
		&cam_ife_csid_lite_690_path_irq_reg_info[CAM_IFE_PIX_PATH_RES_RDI_5],
		},
	.buf_done_irq_reg_info = &cam_ife_csid_lite_690_buf_done_irq_reg_info,
	.cmn_reg                              = &cam_ife_csid_lite_690_cmn_reg_info,
	.csi2_reg                             = &cam_ife_csid_lite_690_csi2_reg_info,
	.path_reg[CAM_IFE_PIX_PATH_RES_IPP]   = NULL,
	.path_reg[CAM_IFE_PIX_PATH_RES_PPP]   = NULL,
	.path_reg[CAM_IFE_PIX_PATH_RES_RDI_0] = &cam_ife_csid_lite_690_rdi_0_reg_info,
	.path_reg[CAM_IFE_PIX_PATH_RES_RDI_1] = &cam_ife_csid_lite_690_rdi_1_reg_info,
	.path_reg[CAM_IFE_PIX_PATH_RES_RDI_2] = &cam_ife_csid_lite_690_rdi_2_reg_info,
	.path_reg[CAM_IFE_PIX_PATH_RES_RDI_3] = &cam_ife_csid_lite_690_rdi_3_reg_info,
	.path_reg[CAM_IFE_PIX_PATH_RES_RDI_4] = &cam_ife_csid_lite_690_rdi_4_reg_info,
	.path_reg[CAM_IFE_PIX_PATH_RES_RDI_5] = &cam_ife_csid_lite_690_rdi_5_reg_info,
	.need_top_cfg = 0,
	.rx_irq_desc        = &cam_ife_csid_lite_690_rx_irq_desc,
	.path_irq_desc      = cam_ife_csid_lite_690_path_irq_desc,
	.num_top_err_irqs   = cam_ife_csid_690_lite_num_top_regs,
	.num_top_regs       = 1,
	.num_rx_regs        = 1,
};
#endif /* _CAM_IFE_CSID_LITE_690_H_ */
